"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2024-07-21 12:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ingest_status', sa.String(length=50), nullable=False),
    sa.Column('pinecone_namespace', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_hash')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_user_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('document_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('result_location', sa.String(length=255), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_type', 'jobs', ['status', 'job_type'], unique=False)
    op.create_table('job_artifacts',
    sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=True), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('blob_json', sa.JSON(), nullable=True),
    sa.Column('blob_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_artifacts')
    op.drop_index('ix_jobs_status_type', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
